### ISSUE TITLE
Time not frozen when "pause" is used.

### ISSUE THREAD

**Issue by PenguinOWN** [DrCas/WilburBot-Issues#2]
Time & Date of Issue (Day/Month/Year Hour:Minute): 07/09/2020 1:21am GMT+2
Island Name: Junebug
Discord tag: Reported by: PenguinOWN#1337, user in queue: MlleCanary#5356, host of the queue was: unknown
Issue Description: Whenever host does "pause" and doesnt "resume" in time, participants will be kicked out for taking too long time on hosts island due to their first session running out of time (time isn't paused and keeps ticking) and they lose their spot to sell/buy.

Image of what happened (Use imgur or similar): https://imgur.com/a/bA33CzY

**Comment by DrCas** [comment]
Bug has been patched in upcoming version. Thanks for the report, closing the issue now. Should the issue return please reopen this
