### ISSUE TITLE
Timer isn't working when session is resumed after a pause.

### ISSUE THREAD

**Issue by PenguinOWN** [DrCas/WilburBot-Issues#3]
Time & Date of Issue (Day/Month/Year Hour:Minute): 06.09.2020 11:25pm GMT+2
Island Name: Poni Isle
Island Price: 605
Discord tag: Reported by and visitor: PenguinOWN#1337, hosted by: Shay#0258
Issue Description: When the host puts their island on pause and resumes their session, the timer on the second message is frozen and doesnt work (stuck at 00:00).

Image of what happened (Use imgur or similar): https://imgur.com/a/6pyGUuB

**Comment by DrCas** [comment]
Bug has been patched in upcoming version. Thanks for the report, closing the issue now. Should the issue return please reopen this issue
